version: '3'
services:
  flask:
    build: .
    container_name: flask
    environment:
      - PYTHONUNBUFFERED=True  

    restart: on-failure
    
    ports:
      - "5000:5000"
    command: python3 app.py